#!/usr/bin/env bash
set -Eeuo pipefail

###############################################################################
# Deployment Framework Paths
###############################################################################

DEPLOYMENT_LOG_DIRECTORY="/var/log/tinqa-deploy"

DEPLOYMENT_DIAGNOSTICS_DIRECTORY="${DEPLOYMENT_LOG_DIRECTORY}/diagnostics"

DEPLOYMENT_REPORT_DIRECTORY="${DEPLOYMENT_LOG_DIRECTORY}/reports"

DEPLOYMENT_ROLLBACK_DIRECTORY="${DEPLOYMENT_LOG_DIRECTORY}/rollback"

export DEPLOYMENT_LOG_DIRECTORY
export DEPLOYMENT_DIAGNOSTICS_DIRECTORY
export DEPLOYMENT_REPORT_DIRECTORY
export DEPLOYMENT_ROLLBACK_DIRECTORY