#!/usr/bin/env bash

EXCLUDED_PATTERNS=(

    # Git
    ".git"
    ".github"
    ".gitignore"
    ".gitattributes"

    # IDE
    ".idea"
    ".vscode"

    # Python
    "venv"
    "__pycache__"
    "*.pyc"
    "*.pyo"
    "*.pyd"

    ".pytest_cache"
    ".mypy_cache"
    ".ruff_cache"
    ".coverage"

    # macOS
    ".DS_Store"

    # Generated
    "logs"
    "backup"
    "temp"

)

export EXCLUDED_PATTERNS